invoiceVersion: "4.5.17"
#ingressClass: "private" #Uncomment this line if you want to target a specific ingress
hostnames: 
  - invoice.example.com
certmanager:
  issuerType: ClusterIssuer
  issuerName: letsencrypt-stage # Change with the name of your clusterIssuer
storage:
  storageClassName: hostpath # Change with the name of the storageClass you want to use
  size: 2Gi
apps:
  mysql:
    image:
      repo: mysql
      tag: 5
    env:
      - name: MYSQL_DATABASE
        value: "ninja"
      - name: MYSQL_ROOT_PASSWORD
        value: "Needtobechanged" # Need to be changed for production environment
      - name: MYSQL_USER
        value: "ninja"
      - name: MYSQL_PASSWORD
        value: "Needtobechanged" # Need to be changed for produciton environment
  nginx:
    image:
      repo: nginx
      tag: "1.17.8"
  invoice:
    image:
      repo: invoiceninja/invoiceninja
    env:
      APP_ENV=production
      APP_DEBUG=false
      APP_URL=https://invoice.example.com/
      APP_KEY=Needtobechanged
      APP_CIPHER=AES-256-CBC
      APP_LOCALE=fr
      DB_TYPE=mysql
      DB_STRICT=false
      DB_DATABASE=ninja
      DB_USERNAME=ninja
      DB_PASSWORD=Needtobechanged
      GOOGLE_MAPS_ENABLED=false
      LOCK_SENT_INVOICES=true
      TRUSTED_PROXIES=0.0.0.0/0
