invoiceVersion: "4.5.17"
hostnames: 
  - invoice.example.com
certmanager:
  issuerType: ClusterIssuer
  issuerName: letsencrypt-stage # Change with the name of your clusterIssuer
storage:
  storageClassName: hostpath # Change with the name of the storageClass you want to use
  size: 2Gi
apps:
  mysql:
    image:
      repo: mysql
      tag: 5
    env:
      - name: MYSQL_DATABASE
        value: "ninja"
      - name: MYSQL_ROOT_PASSWORD
        value: "kljlknesLKHJkkjsdf" # Need to be changed for production environment
      - name: MYSQL_USER
        value: "ninja"
      - name: MYSQL_PASSWORD
        value: "ninjapass" # Need to be changed for produciton environment
  nginx:
    image:
      repo: nginx
      tag: "1.17.8"
  invoice:
    image:
      repo: invoiceninja/invoiceninja
    env:
      - name: APP_ENV
        value: 'production' # production or development
      - name: APP_DEBUG
        value: 1 # 1 or 0
      - name: APP_URL
        value: 'http://localhost:8000'
      - name: APP_KEY
        value: 'Needtobechanged' # This key need to be change !!! This one will not work !
      - name: APP_CIPHER
        value: 'AES-256-CBC'
      - name: TRUSTED_PROXIES
        value: '0.0.0.0/0' # Need to be adapt to your environment. This value is too open for production environment.
      - name: DB_TYPE
        value: 'mysql'
      - name: DB_USERNAME
        value: 'ninja'
      - name: DB_PASSWORD
        value: 'ninjapass' # Should be the same as MYSQL_PASSWORD
      - name: DB_DATABASE
        value: 'ninja'
      - name: MAIL_HOST
        value: mailserver
      - name: MAIL_DRIVER
        value: smtp
      - name: MAIL_FROM_NAME
        value: 'InvoiceNinja'
      - name: MAIL_FROM_ADDRESS
        value: 'finance@example.com'
