# This is the definition of the required ssl certificate for the invoice system
# It will be issued by cert-manager

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ include "invoice-ninja.fullname" . }}-certificates
spec:
  secretName: {{ include "invoice-ninja.fullname" . }}-certificates
  renewBefore: 1440h # 60d
  commonName: "{{ first (required "hostname" .Values.hostnames) }}"
  dnsNames:
{{- range .Values.hostnames }}
  - "{{ . }}"
{{- end }}
  issuerRef:
    kind: {{ .Values.certmanager.issuerType }}
    name: {{ .Values.certmanager.issuerName }}
