apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "invoice-ninja.fullname" . }}-data"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: "{{ .Values.storage.size }}"
  storageClassName: "{{ .Values.storage.storageClassName }}"
